# src/AppBundle/Resources/config/services.yml
parameters:
    uploaded_resources_dir: '%kernel.project_dir%/web/uploads'
    uploaded_resources_allowed_mime_types:
        - image/jpeg
        - image/gif
        - image/png
    uploaded_resources_max_width: 1920
    uploaded_resources_max_height: 1080
    uploaded_resources_max_weigth: 20971520
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    AppBundle\EventListener\ImageUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postLoad }
    AppBundle\Service\FileUploader:
        arguments:
            $targetDir: '%uploaded_resources_dir%'
    AppBundle\Service\ZipArchiver:
        arguments:
            $targetDir: '%uploaded_resources_dir%'